# Generated by Django 2.2 on 2019-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uri', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=4096)),
            ],
        ),
    ]
